### ISSUE TITLE
People Counter

### ISSUE THREAD

**Issue by vikramgk007** [LukashenkoEvgeniy/People-Counter#1]
The code is executing... But, i am not getting any output...

By the way, which version of opencv you used?? and which version of Python you used??

Kindly tell me what to do, to run the code....

**Comment by amalsoula** [comment]
@LukashenkoEvgeniy 
its working buti want to execute it with live stream what i need to add ?

**Comment by LukashenkoEvgeniy** [comment]
if you use rtsp  you must put your url connection string instead **camera = cv2.VideoCapture("test2.mp4")**. For example **camera = cv2.VideoCapture("rtsp://login:password@ip_camera:port/h000")**

**Comment by amalsoula** [comment]
Thank u for ur reply but I work on raspberry pi and pi camera

**Comment by Bladechou** [comment]
@LukashenkoEvgeniy 
Nice job. May you send me the reference papers.

**Comment by sbrimstone** [comment]
> Thank u for ur reply but I work on raspberry pi and pi camera

Its been a while but did you make any progress with the Raspberry Pi and Pi Camera?
