### ISSUE TITLE
raspberry-pi3 how to grap /dev/video0

### ISSUE THREAD

**Issue by dahili** [LukashenkoEvgeniy/People-Counter#11]
raspberry-pi3 works with http stream url
please tell me how to grap /dev/video0 directly

**Comment by LukashenkoEvgeniy** [comment]
For grabbing video I use Rtsp stream from camera and put it into VideoCapture
Example:
```python
camera = cv2.VideoCapture("rtsp://admin:password@IP-address:Port/tcp/av0_0") 
```
