### ISSUE TITLE
how to manually draw lines (blue and red)

### ISSUE THREAD

**Issue by bit-scientist** [LukashenkoEvgeniy/People-Counter#13]
Thanks @LukashenkoEvgeniy 
Could you show the place in code where I can draw my lines manually. I can't seem to find its place. 
I should draw two horizontal lines a bit above the center of a video.

**Comment by Andreu35** [comment]
Centered Vertical line: 
`cv2.line(frame, (width // 2, 0), (width // 2, width), (250, 0, 1), 2)  # blue line
cv2.line(frame, (width // 2 - 50, 0), (width // 2 - 50, width), (0, 0, 255), 2)  # red line`
