### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wdibi** [LukashenkoEvgeniy/People-Counter#2]
_, cnts, _ = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack

**Comment by juanicotolengo** [comment]
@wdibi , it seems that you're using an oldest openCV library. The error means that you're expecting 3 values, but the method findContours just return 2. Solution: remove the first variable

**cnts, _ = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)**
