### ISSUE TITLE
underedtanding the numbers

### ISSUE THREAD

**Issue by Ayanzadeh93** [LukashenkoEvgeniy/People-Counter#3]
I'm trying to use your code on my own video, I need to change the blue and red line to fit with my video. Unfortunately I don’t understand the values and logic behind your cod in testIntersectionOut() and testIntersectionIn(). I would appreciate if you could help me with this. here are the lines that are suitable for my data and i need to change the mentioned functions according to this lines:

        cv2.line(frame, (1, 0), (width, 450), (250, 0, 1), 2) #blue line
        cv2.line(frame, (- 50, 0), (width - 50, 450), (0, 0, 255), 2)#red line

**Comment by krilliaz** [comment]
We are having the same issue, we dont quite understand the meaning behind the formula to calculate the intersection, would you mind explaining how we could change the values accordingly?

**Comment by SeanMulkerrin** [comment]
I believe the logic is in the testIntersectionOut and testIntersectionIn methods, The lines drawn on the screen are just a visual aid for us, I just can't make sense of  res = -450 * x + 400 * y + 157500

**Comment by kksu49** [comment]
I wish it can me more clear about the res function, how it works, so I can switch to my interest region

**Comment by kksu49** [comment]
based on the name (intersection)  I guess it's a area formula ~

**Comment by kksu49** [comment]
x and y is the position of red point were it on screen,  if it's top left (x=0,y=0)   so define max region where the red point can go. 450 is the y max hight  400 is half of width from(800).
you can find where is x and y by print it . 
then you get some max value , and because its a ugly big negative number   you trim it to a smaller nice number just for look better ,  and make it fit with your if statement.

**Comment by singireddysravankumar** [comment]
How to change the lines to in horizontal please can you tell me in detail?? 
Already i tried to change x and y values but the lines positions are not changing

**Comment by vinaywadhwa** [comment]
i have spent a day or two with the program - and have a bit of understanding.. i now understand what he is trying to do here - mind you, i believe the logic being used here is kind-of flawed.. but let me explain anyway.. this is basically what is happening in the program
- draw 2 close lines on the frame
- count as "IN" if the moving object comes close to the red line (the line on the left)
- count as "OUT" if the moving object comes close to the blue line (the line on the right)

This is the logic
- As soon as the video feed starts, take the very first frame as the "reference" frame.. say F
- compare every further frame with the initial frame to identify moving objects.. 
- calculate the centre point of moving objects
- check if the centre point is within a certain distance from either of the two lines and count it as a "IN" or "OUT" as per the logic explained above.. 

The flaw in the logic is - 
- If the object moves very slow and REMAINS close to the line for more than a single frame, the "IN" and/or "OUT" will be counted twice.
- also, if the object moves very fast and none of the frame captures it near the red or blue line, the entry/exit will not be counted .. eg- someone coming running in..

So - the testIntersectionIn & testIntersectionOut functions are plotting the points in the equations of the red and blue lines (the line equations are in the form y = mx + c) .. If the 'res' comes out to be zero, it means the point lies on the line... if not, it means it somewhere outside the line..  i'm not exactly sure how the author arrived at the '550' magic number, but he's just trying to check if the point is close to the line, if not ON the line..)

i will try to post a pull request which performs slightly better (i keep a timer + last frame position to avoid multiple counting), i place the reference line at other positions..also the code would be a bit more self-explanatory

**Comment by martysyuk** [comment]
@vinaywadhwa can you share your code please.

**Comment by dhar24** [comment]
It's very simple geometrical tactic. These functions are nothing but line equations. If two points are given in coordinate system, you can get equation of line. Formula of line equation is: 
y=mx+c or say y-y1=[(y2-y1)/(x2-x1)]*(x-x1). In the code points are (400,0) and (800,450) so evaluate the equation.

Now it's you put any coordinate in lines equation(y-mx-c) and check whether it's +ve or -ve, will tell which side of line that coordinate exists.
