### ISSUE TITLE
picamera?

### ISSUE THREAD

**Issue by gorkie34** [LukashenkoEvgeniy/People-Counter#4]
how can i use picamera in this project

**Comment by AlabhyaVaibhav** [comment]
You can use the following : 
1. Install the picamera library _pip install "picamera[array]"_ 
Using picamera[array] so as to use the sub modules in OpenCV
2. Import the following 
_from picamera.array import PiRGBArray
from picamera import PiCamera_
3. camera = PiCamera()
And now you can do other stuff.

Hope it help :)

**Comment by JonSim495** [comment]
I've included the 2 import and add in the camera = PiCamera(), I get an error AttributeError: 'PiCamera' object has no attribute 'read'.
Please provide assistance...
