### ISSUE TITLE
Keep getting an error "integer argument expected, got float"

### ISSUE THREAD

**Issue by imkevinabraham** [LukashenkoEvgeniy/People-Counter#6]
when trying to run the code I get an error that reads "integer argument expected, got float". I am using python 3. Would you know what is causing this issue?

**Comment by singireddysravankumar** [comment]
Change these lines  cv2.line(frame, (width // 2, 0), (width, 450), (250, 0, 1), 2) #blue line
        cv2.line(frame, (width // 2 - 50, 0), (width - 50, 450), (0, 0, 255), 2)#red line


        rectagleCenterPont = ((x + x + w) //2, (y + y + h) //2)
        cv2.circle(frame, rectagleCenterPont, 1, (0, 0, 255), 5)

        if(testIntersectionIn((x + x + w) // 2, (y + y + h) // 2)):
            textIn += 1

        if(testIntersectionOut((x + x + w) // 2, (y + y + h) // 2)):

Give double slash

**Comment by Luthfiansyah** [comment]
Thanks A Lot @sadhanareddy007 :)

**Comment by LukashenkoEvgeniy** [comment]
@AlabhyaVaibhav fix it. Changes in master

**Comment by Harshitsriv007** [comment]
> Change these lines cv2.line(frame, (width // 2, 0), (width, 450), (250, 0, 1), 2) #blue line
> cv2.line(frame, (width // 2 - 50, 0), (width - 50, 450), (0, 0, 255), 2)#red line
> 
> ```
>     rectagleCenterPont = ((x + x + w) //2, (y + y + h) //2)
>     cv2.circle(frame, rectagleCenterPont, 1, (0, 0, 255), 5)
> 
>     if(testIntersectionIn((x + x + w) // 2, (y + y + h) // 2)):
>         textIn += 1
> 
>     if(testIntersectionOut((x + x + w) // 2, (y + y + h) // 2)):
> ```
> Give double slash, When we give double slash it will take as integer otherwise it will consider as float...
> This can help you

x is not define

**Comment by LukashenkoEvgeniy** [comment]
```python
(x, y, w, h) = cv2.boundingRect(c)
````
x - its height of rectangle
