### ISSUE TITLE
Number meaning

### ISSUE THREAD

**Issue by metanite** [LukashenkoEvgeniy/People-Counter#7]
What is the meaning of the values 157500 and 180000?

**Comment by dhar24** [comment]
That means you didn't understand what is the meaning of coefficients of x & y. Answer lies in functions he made.
It's very simple geometrical tactic. These functions are nothing but line equations. If two points are given in coordinate system, you can get equation of line. Formula of line equation is:
y=mx+c or say y-y1=[(y2-y1)/(x2-x1)]*(x-x1). In the code points are (400,0) and (800,450) so evaluate the equation.

Now it's you put any coordinate in lines equation(y-mx-c) and check whether it's +ve or -ve, will tell which side of line that coordinate exists.
