### ISSUE TITLE
counting methods logic

### ISSUE THREAD

**Issue by projecthelp123** [LukashenkoEvgeniy/People-Counter#8]
I understand almost all of the code apart from the vital part...
I understand that the co ordinates of the circle is passed in as the methods parameters, but i don't understand what the methods are doing exactly. Can you explain the calculations and the range of res at all? And why -450, +400 and + 157500, and + 180000. Why these particular numbers and what calculation in being made? What if two people walk past at the same time also? What happens to these numbers if i change the height variable or change the frames width, or i reduce/increase the contourArea in the if statement? Sorry im making this complicated, 

thanks very much

def testIntersectionIn(x, y):
    res = -450 * x + 400 * y + 157500
    if((res >= -550) and  (res < 550)):
        return True
    return False

def testIntersectionOut(x, y):
    res = -450 * x + 400 * y + 180000
    if ((res >= -550) and (res <= 550)):
        return True
    return False

**Comment by LukashenkoEvgeniy** [comment]
https://github.com/LukashenkoEvgeniy/People-Counter/issues/7
